### PR TITLE
Created manual entry form and wrote tests for it

### LINKED ISSUE #17: DJ: Manual Entry Form
As a DJ, I would like to be able to enter a song and artist manually if it is not present in the Spotify database, so that I am free to add any song I choose. I would like an interface to alternate between the search bar and the manual entry form (button, switch, etc.)

Acceptance criteria: 
- selecting manual entry mode vs. search mode changes the appearance of the page accordingly to allow the requested behavior
- manually adding a song creates an object with valid song structure, including a placeholder album artwork image

Difficulty Score: 2

### LINKED ISSUE #18: DJ: Search Bar
As a DJ, I would like to be able to search in one field by either title, artist, or album so that I can get the most accurate results possible. Specifically, after I click the search button (or if feasible, as I type) I would like to see the 10 best matches for my search appear in a dropdown menu.

Acceptance criteria:
- Searching in both the title and artist fields returns a dropdown menu of the top 10 most relevant results

Change lastfm API queries to Spotify API queries. Make single search bar that returns top 10 results, where DJ can click on one to add it to the playlist.

Difficulty Score: 4

### PR DESCRIPTION
**Pull request by majacannavo**

### CODE REVIEW

**Comment by brendanphilbin** [comment]
That looks good, great work Maja! One thing I will say (and this applies to the search bar as well) is that I think we should try to use MaterialUI as much as possible. They have really nice looking text fields (https://material-ui.com/components/text-fields/) that I think we should lean towards as opposed to standard HTML <input> tags. The functionality and tests look awesome.

**Comment by mylesstokowski** [comment]
Agreed about MaterialUI, I'm taking a stab now at implementing that for ManualEntry - should be quick

**Comment by SimonScharf** [comment]
Looks good to me as well! My only question is if we should merge this branch into main because it currently does not use the searchBar or songAdder functionalities which we probably want to be integrated altogether on the main branch. I feel like it makes more sense to keep working on this branch a little more to integrate the different pieces before merging it into main, but if y'all disagree thats fine too and we can merge it.

**Comment by mylesstokowski** [comment]
Yeah I hear you on that Simon. We definitely need to incorporate the searchBar and songAdder functionality, probably at the same time that we switch to using the Spotify API. Maja and I were planning on taking that on – I'm happy with waiting to do that before merging

**Comment by majacannavo** [comment]
Good point Simon--also sounds good to me to work on integrating the Spotify API before merging.

**Comment by mylesstokowski** [comment]
Hey y'all Maja and I just finished up with connecting to the Spotify API. This branch adds the spotify api search feature and manual entry. The real challenge was getting spotify authentication to work, part of this involved adding an API route `api/auth`.

In this branch, we also removed old approaches to adding songs from the first sprint.

**Comment by brendanphilbin** [comment]
Looks good to me!

**Comment by SimonScharf** [comment]
Love the updated changes!

**Pull request merged**
