### PR TITLE
Playlist explorer

### PR DESCRIPTION
**Pull request by brendanphilbin**
Simon and I pair programmed today and got the core functionality down for the PlaylistExplorer (connected to the backend). We need to make it look better and write tests but we modified Song.js so we thought an early merge would be beneficial.

### CODE REVIEW

**Comment by brendanphilbin** [comment]
Fixing errors now.

**Comment by mylesstokowski** [comment]
I like how you recycled the song component - clean. Pulled the changes and played around with the playlist explorer, LGTM.

**Comment by Ntare62** [comment]
it looks pretty good to me. once we finish the authentication, we can make it that only the person who logged in can access the dj page

**Review by majacannavo — COMMENTED** [review]
Looks great, thanks Brendan and Simon! One question I have is whether we can make the links between the DJ page and the home page into buttons so they're easier to click?

**Comment by mylesstokowski** [comment]
> Looks great, thanks Brendan and Simon! One question I have is whether we can make the links between the DJ page and the home page into buttons so they're easier to click?

Agreed, I think this might be more intuitive

**Comment by brendanphilbin** [comment]
Definitely myles, i just hastily threw them in as placeholders. I can make them nicer tomorrow

**Pull request merged**
