### PR TITLE
Schedule component updated stylings

### PR DESCRIPTION
**Pull request by SimonScharf**
Fixed refresh bug and added more styling to component

### CODE REVIEW

**Comment by mylesstokowski** [comment]
Sweet, thanks for this! Just have a few questions.

It looks like a bunch of files were changed in the seeds, migrations and data directories - I think this is all just white space changes that were automatically applied, as well as linting fixes? 

I think the important changed files to look at are schedule.js and schedule.test.js? Any others?

I notice there's a merge conflict in PlaylistExplorer.js. I'm assuming any changes you made to that were just spacing so can probably just fix that by using the version of PlaylistExplorer.js from main?

**Comment by SimonScharf** [comment]
> Sweet, thanks for this! Just have a few questions.
> 
> It looks like a bunch of files were changed in the seeds, migrations and data directories - I think this is all just white space changes that were automatically applied, as well as linting fixes?
> 
> I think the important changed files to look at are schedule.js and schedule.test.js? Any others?
> 
> I notice there's a merge conflict in PlaylistExplorer.js. I'm assuming any changes you made to that were just spacing so can probably just fix that by using the version of PlaylistExplorer.js from main?

Oops, when I merged Brendan's PR that created some conflicts in mine. I just fixed them now. Yes, the only important files are the schedule, schedule.test, and the _document.js page. Everything else is linting and white space changes automatically applied by prettier that doesn't change functionality.

**Comment by mylesstokowski** [comment]
Ok gr8 then LGTM!

**Comment by brendanphilbin** [comment]
Looks good to me

**Pull request merged**
