### PR TITLE
Auth redir

### PR DESCRIPTION
**Pull request by Ntare62**
I just added a way to redirect the users if they are not logged in. I also modified some modifications related to authentication on the listener and dj page.

### CODE REVIEW

**Comment by brendanphilbin** [comment]
Looks good to me. Nice job

**Comment by mylesstokowski** [comment]
Reviewed the code and interacted w it, looks great to me!

**Comment by SimonScharf** [comment]
Looks great to me, I love the error message format!

**Comment by majacannavo** [comment]
Looks good to me, thanks so much Assadou!

**Comment by majacannavo** [comment]
One thing I noticed is that the "signed in as _____" message is right next to the the sign-out button without any spacing but maybe we can fix this after merging when we do the final styling?

**Comment by majacannavo** [comment]
Assadou would you mind taking care of the conflicts with main before we merge? Thanks so much!

**Comment by brendanphilbin** [comment]
Just pulled and played around with it. LGTM

**Comment by mylesstokowski** [comment]
LGTM!

**Pull request merged**
