### PR TITLE
Playlist explorer

### LINKED ISSUE #34: Playlist Explorer
As a listener I want to be able to view playlists of past songs played on the radio station. I want to be able to select a show, select a date on which that show aired, and be presented with the list of songs played during that window so that I can decide whether or not I want to tune in to the next airing of the show.

### PR DESCRIPTION
**Pull request by brendanphilbin**
PlaylistExplorer component completed, has conflicts that need to be resolved. Complete testing suite and no refresh bug.

### CODE REVIEW

**Comment by mylesstokowski** [comment]
Brendan just clarified to me - this PR modifies the existing playlist explorer with restyling and the addition of tests

**Comment by mylesstokowski** [comment]
Looks good to me!

**Comment by majacannavo** [comment]
Overall looks good! Not sure if this is an error unique to me, but when I pulled the code and tried to run it, I was unable to click on a show without getting an error saying that the show could not be found. Is this happening to others?

**Comment by majacannavo** [comment]
> Overall looks good! Not sure if this is an error unique to me, but when I pulled the code and tried to run it, I was unable to click on a show without getting an error saying that the show could not be found. Is this happening to others?

Wait, never mind, I'm not getting that error anymore. It looks great--the only thing I'm wondering about is whether it would be possible to order the dates in chronological order in the dropdown menu.

**Comment by brendanphilbin** [comment]
> > Overall looks good! Not sure if this is an error unique to me, but when I pulled the code and tried to run it, I was unable to click on a show without getting an error saying that the show could not be found. Is this happening to others?
> 
> Wait, never mind, I'm not getting that error anymore. It looks great--the only thing I'm wondering about is whether it would be possible to order the dates in chronological order in the dropdown menu.

That's a good idea, we can definitely do that in the future (as well as add more information to the dropdown like DJ name).

**Comment by SimonScharf** [comment]
Love all the tests, they look very thorough. I am going to go ahead and merge this only because we talked about merging more code into main so that we don't get too far behind. We can try to add the dates in chronological order in the next PR, because I also like that idea.

**Pull request merged**
