### PR TITLE
Authentication functions

### PR DESCRIPTION
**Pull request by Ntare62**

### CODE REVIEW

**Comment by Ntare62** [comment]
I just finished authentication. I added the tests and a database for keeping track of the djs allowed to access the dj page. Right now the branch does not pass travis checks, so please do not merge it yet. I am not sure how to solve those checks. So, if anyone can figure out, it would be appreciated. In the meantime, I thought we could start commenting on different parts since it is a lot of files.

**Comment by brendanphilbin** [comment]
Looks great Assadou, seems like that was a ton of work so thanks so much!

**Comment by mylesstokowski** [comment]
Great you got the merge conflict resolved, that seemed tricky. Tried to pull it and interact with it but pretty sure my issue was just with environment variables so don't think it's worth holding this up.

Awesome work - clearly a lot here! Looks good to me

**Comment by mylesstokowski** [comment]
Update: set it up and logged in with Assadou's help!

**Comment by SimonScharf** [comment]
Authentication works great for me, and seems to work great for everyone else, so I'm going to go ahead and merge the PR. Thanks so much for all the hard work Assadou!

**Pull request merged**
