### PR TITLE
added functionality to add a new playlist

### PR DESCRIPTION
**Pull request by majacannavo**
Hey guys, I've been working on functionality to add a new playlist. If you click the "Add Playlist" button then the search bar appears and a new playlist is created in the database. Currently it's tough to create a lot of playlists for the sake of testing because then we run into duplicate time windows, which is why I edited the date in CreatePlaylist() in playlist-table-utils.js for testing purposes. (I marked where I changed it so that we can change it back when we have things a bit more figured out.) I've also been changing the currentShowId state in dj.js around when I want to add a new playlist to avoid the time conflict thing (the current show isn't getting set by any other means yet). If you hit the "Cancel" button then the current playlist (the one being constructed) is deleted and the search bar goes away. So far the adding and deleting of playlists (not individual songs) is the only part connected to the backend, but next I'm planning to work on sending songs directly to the database when they're added. I figured it would be a good idea to get this merged sooner rather than later though for the sake of consistency between branches.

### CODE REVIEW

**Comment by mylesstokowski** [comment]
pulled it and played around - looks good to me!

**Comment by Ntare62** [comment]
Thank you Maja, this looks good to me. We should probably think about writing tests for these functionalities as well.

**Comment by brendanphilbin** [comment]
Looks good. I believe the backend function we have "addSongToPlaylist" does everything we need for adding a song to an existing playlist. I don't believe we have an endpoint for that yet though. I'll go ahead and merge this branch given that we've had several comments already

**Comment by brendanphilbin** [comment]
Should I delete the branch or will you continue working in this one?

**Comment by brendanphilbin** [comment]
> Looks good. I believe the backend function we have "addSongToPlaylist" does everything we need for adding a song to an existing playlist. I don't believe we have an endpoint for that yet though. I'll go ahead and merge this branch given that we've had several comments already

One thing to add is that the addSongToPlaylist currently checks Spotify ID's for uniqueness so if we aren't going to go along that route then we should decide soon (Spotify ID vs. Title-Artist-Album unique combo)

**Comment by majacannavo** [comment]
Thanks Brendan! I'm down to use the Spotify IDs and just do a concatenation of title+artist+album for manual entries if that works. The addSongToPlaylist function looks great--thanks for writing such a comprehensive set of database utility functions. I'll delete this branch and make a new one for the next phase.

**Pull request merged**
