### PR TITLE
Schedule

### LINKED ISSUE #24: Develop front-end design of schedule
Create the RadioSchedule component and design the basic structure using material-ui components so that once we sort out the backend database we can plug in values and it will look nice.

### LINKED ISSUE #40: As a user, I would like to see all the shows that are playing each week so that I know when to tune in for my favorite shows

### PR DESCRIPTION
**Pull request by mylesstokowski**
Hey all. Matthew and I worked on getting the schedule connected to the back end. Basically we took the Material UI design that Simon and Matthew had worked on previously and hooked it up to existing API routes.

Thanks for taking a look!

### CODE REVIEW

**Comment by brendanphilbin** [comment]
That looks great! One thing I will ask is do we plan on having the descriptions for each show appear somewhere? If not, I suppose we can just take that out of the database

**Comment by mylesstokowski** [comment]
Good point, I agree that we should add that. Part of me thinks in the spirit of frequent merges, maybe we merge this first and I (or if anyone else is eager to) do that in a new branch?

**Review by majacannavo — COMMENTED** [review]
The code looks great--thanks guys! Unfortunately, though, when I pulled the changes and tried to run it I got the error "Error: Cannot find module 'babel-plugin-styled-components'". I tried to install the module but it still gave me the error. I checked and my package.json and babelrc files are all up to date with the pull request--do you have any idea what might be going on?

**Comment by SimonScharf** [comment]
Looks great to me!

**Pull request merged**
