### PR TITLE
separated DJ and Home page, added simple links back and forth

### PR DESCRIPTION
**Pull request by brendanphilbin**

### CODE REVIEW

**Review by majacannavo — COMMENTED** [review]
Looks good to me, thanks Brendan!

**Comment by mylesstokowski** [comment]
LGTM, thanks!

**Comment by SimonScharf** [comment]
Thanks so much for doing this, and it looks great to me too but I had a couple questions. 

Was the primary goal of adding links so that we can work on the two pages separately? Because eventually we want to transition to having a listener home page that someone can log-in from and then once they are logged in, they are forwarded to their DJ page. Sorry for my confusion, I might've missed the details during the meeting; I just want to make sure I understand what we are doing fully.

**Comment by SimonScharf** [comment]
I ran it in replit and think it looks great and is ready for merging

**Comment by brendanphilbin** [comment]
My thought would have been that the listener page is default and once someone logs in the button for accessing the dj page appears. I'm not sure if removing the listener page from the DJ's access gives much benefit. If yall think otherwise im open to it

**Comment by brendanphilbin** [comment]
If this merge is alright for the time being though then lets get it merged and discuss the actual design on Tuesday

**Comment by brendanphilbin** [comment]
Anyone can go ahead and merge then. Dont delete the branch though, we'll keep that one open for the PlaylistExplorer

**Pull request merged**
