### PR TITLE
Song database start

### LINKED ISSUE #19: Establish server/database
Get a database up and running for us to store our data. Songs and playlists should be stored in the database.

### PR DESCRIPTION
**Pull request by brendanphilbin**

### CODE REVIEW

**Review by mylesstokowski — COMMENTED** [review]
Looks very cool. My one question (truly a q, I'm not sure the answer) is whether we want to merge old versions of things into main, for example the old_migrations folder

**Comment by brendanphilbin** [comment]
Thats a good point Myles. If Im not mistaken we should have no need for those files anymore but let me check with Assadou so we can thin out the branch to only the files we actually need. We kept those as references as we were walking but I think you're right that we shouldn't merge them

**Comment by SimonScharf** [comment]
Looks great to me. Thanks so much for all of the hard work!

**Comment by mylesstokowski** [comment]
Thanks for removing those files (and all the work on this). Looks good to me!

**Review by majacannavo — APPROVED** [review]
This looks good to me--thanks so much Brendan and Assadou!

**Pull request merged**
